#! /usr/bin/bash 
source /etc/profile
clear

echo "
This NEOVIM is my personal Favorite
sleep 3  

 echo""
 echo""
 echo""
 echo""

echo " This is only for ARCH Users"

echo""
echo""
echo " -  Installing clang and its a c++ environment . You can install your environment"
sleep 3  
echo""
echo""
echo "You can create your own LSP . Please read the LSP section on my github about it"
sleep 3 
 sudo pacman -Sy clang


 sudo pacman -Syu 

 sudo pacman -Sy nodejs
 sudo pacman -Sy ripgrep
 echo ""
 echo ""

if [ ! -d ~/.config/nvim ]; then
  mkdir ~/.config/nvim/
fi

cd ~/.config/nvim/


git clone https://github.com/altaffff/nvim-lazy-Full-on-amazing-IDE-.gitcd

cd ~/.config/nvim/nvim-lazy-Full-on-amazing-IDE-


cp -r init.lua ~/.config/nvim
cp -r lua/ ~/.config/nvim/
cd ~/.config/nvim/

